### ISSUE TITLE
Speak English to Me, The Secret World of Programmers

### ISSUE THREAD

**Issue by OrionRandD** [npmaile/blog#7]
I did not find a place to comment on your post...
But, the maim problem IMHO are not software themselves, but it is a matter of mindset...
Windows and MacOS worlds, especially the former, were design to raise generations of illiterate IT people...
They have detonated their narrow minds with the "point-and-click" computer life-style that is hard to knock down...
If schools, universities and government agencies do not fight this trend, I bet they will not - because they already have been bought by these big players, we will end-up in a "Idiocracy" < https://en.wikipedia.org/wiki/Idiocracy  > society...
But, do not be fooled, because I also have crossed and dealt with people who have IT computer degrees who also did not know what unix/Linux, openSource, FS and the like was and were and are slaves of M$ in their personal life and work...
Do not conclude that Programmers everywhere in the world know their craft in a deep level. 
I also have seen some of them who do not know how to use a terminal for installing and configuring simple things...
Sorry to comment your post here...

**Comment by Edim7** [comment]
I'd argue we all have use for levels of abstractions. Abstracting is the way we deal with life. Some people might call em metaphors, some might use the term black box solutions. For better or for worse we don't need to inherently understand the things we are using. TO us programmers / software devs that are curious to tinker there is no other way but to learn and try and understand as much as we can to why things happened like they do. However, just because we know why a machine operates in a certain way doesn't mean we understand the whole world. 

More precisely just because we are better at typing and interfacing with machines doesn't mean we understand the World better or that we are superior to a person that doesn't do the same. 

I do however have a solution to pitch to you which would solve the .md sharing issues. 
1. Buy a domain, or use the one you have
2. Spin up this repo as your blog
3. Profit?

When you have to share something public written in md send a url instead of a file. You can host it somewhere else as well if its something requiring privacy and authentication of the access.

Its pretty easy and using vanilla technologies might be refreshing. I did this with https://github.com/Aurora-Borealis-Dev/Aurora-Borealis-Dev.github.io on auroraborealis.dev 
I keep lying to myself that I'll finish the site soon <sup>TM</sup> and turn it into something more than just a landing page

**Comment by OrionRandD** [comment]
I already have a blog...
Anyways, did think my comment was sound?
As I told you, I did not find another way to write to you...
In fact, after posting that, I got your email address...

**Comment by nhdez** [comment]
I just want to know if someone can have a look at my printer

**Comment by npmaile** [comment]
> I just want to know if someone can have a look at my printer

no
